### ISSUE TITLE
Unable to construct an object using new

### ISSUE THREAD

**Issue by apostrophesoftware** [sebastienros/jint#522] opened 2018-07-26 19:17 UTC
Hi

I am attempting to create custom objects in JavaScript and am not able to get it to work!

I am adding class references to my JIint instance to enable me to create some objects in my scripts.  When I call the constructor I get the following error **The object can't be used as constructor**.

My script is below

`var ttns = importNamespace('NamespaceName');

var tt = erp.create('ObjectName');

var product = new ttns.Product(null, null, null, 'Test Product', '', 0, 0, 0, false, null, false, null, null, null);

result = erp.createProduct(tt, product);`

My C# code is

`m_engine.SetValue("NamespaceName", new NamespaceReference(m_engine.Engine, "PathToNamespace"));`

Thanks

**Comment by ViceIce** [comment] 2018-08-24 09:17
Looks like a duplicate of #265

**Comment by sebastienros** [comment] 2018-08-24 16:43
@ViceIce I think you are correct, assemblies need to be imported too, we can't let Jint iterate over all loaded assemblies.

@apostrophesoftware Please re-open this issue if this was not the solution.

**Closed by sebastienros** 2018-08-24 16:43 UTC
