### ISSUE TITLE
Calling task method in js is not as expected

### ISSUE THREAD

**Issue by scgm0** [sebastienros/jint#1804] opened 2024-03-13 18:54 UTC
v3.0.1

code:
```
var engine = new Engine();
engine.SetValue("log", new Action<string>(Log));
engine.SetValue("delay", (int delay) => Task.Delay(delay));
engine.Modules.Add("main", @"
log(1);
delay(5000);
log(2);
");
engine.Modules.Import("main");
Log("3");
void Log(string s) => Console.WriteLine($"{DateTime.Now} {s}");
```
log:
```
2024/3/14 02:49:05 1
2024/3/14 02:49:05 2
2024/3/14 02:49:10 3
```
envisage:
```
2024/3/14 02:49:05 1
2024/3/14 02:49:05 2
2024/3/14 02:49:05 3
```

**Comment by lahma** [comment] 2024-03-13 19:04
Could you please send a PR fixing the issue?

**Comment by scgm0** [comment] 2024-03-13 19:15
> Could you please send a PR fixing the issue?

I'll try, but I'm new to dotnet and can't always fix it.

**Comment by sebastienros** [comment] 2024-03-13 19:28
Works with `await delay(5000);`

**Comment by lofcz** [comment] 2024-03-14 08:50
Works as Sebastien suggests since #1787.

**Comment by lahma** [comment] 2024-03-14 08:58
Yep, tasks need to be awaited or otherwise the C# side should handle the blocking, closing as works as intended.

**Closed by lahma** 2024-03-14 08:58 UTC
