### ISSUE TITLE
S15.8.2.15_A7.js CHECK#4 failed when unit test runs with .Net Core 2.1

### ISSUE THREAD

**Issue by AlPecin** [sebastienros/jint#584] opened 2019-01-08 13:57 UTC
Hi,
when I run the unit test project "Jint.Tests.Test262" with .Net Core 2.1 I got an error by S15.8.2.15_A7.js CHECK#4. When ein change to .Net Framework 4.6.1 it works fine. 
I'm searching vor the reason and get the following effect in a console project:

            const double Epsilon = 2.2204460492503130808472633361816E-16;
            double x = 0.5D - Epsilon / 4;
            double y = Math.Round(x);
            Console.WriteLine(y);

Build with .Net Core 2.1 the result from y == 1
build with .Net Framework 4.6.1 the result from y == 0

Knows anybody about this effect?

**Comment by sebastienros** [comment] 2019-01-10 16:17
So this is not an issue with jint but in the DotNet frameworks.

**Comment by sebastienros** [comment] 2019-01-10 16:18
I will ask the devs on the runtime for an explanation, but what usually happens in this case is that it's by design, with very good reasons why this is so.

**Comment by AlPecin** [comment] 2019-01-11 06:07
The issue with jint is that the described unit test with .Net core failed and with .Net Framework is ok.

**Comment by lahma** [comment] 2019-01-11 07:06
@AlPecin unit tests don't fail on my machine and they are run on .NET Core 2.1, just like every build that appveyor tests (all tests are green). You sample programs don't utilize Jint.

**Comment by AlPecin** [comment] 2019-01-11 07:34
@lahma: The example program extracted the reason why the unit test failed and I'm interested if you get on your machine the same results with the example programs.

**Comment by lahma** [comment] 2020-06-22 05:44
Closing as obsolete, we can reopen if problem persists.

**Closed by lahma** 2020-06-22 05:44 UTC
