### ISSUE TITLE
Support for .NET versions 2/3.5

### ISSUE THREAD

**Issue by Willy-Kimura** [sebastienros/jint#223] opened 2015-09-11 20:56 UTC
Hi Sebastien,

Great and amazing work, but I would really really wish that the Interpreter supports versions 2 and 3.5 of the .NET Framework due to XP backward compatibility since Windows XP is not supported with .NET v4.5 and later. I tried running the Interpreter loaded with a couple of scripting APIs built but it kept on raising an Exception stating: ##could not load "System." at Jint..ctor## with a reference to the calling object and Form, only later to realize that it actually required .NET v4.0 to run after testing it on a Windows 8/8.1 machine. Many of us still provide support for Windows XP users through our applications and would want to continue as so. Please please sir and the community at large, consider this as a burning issue, please...

Thank you.

**Comment by Willy-Kimura** [comment] 2015-09-11 20:58
Hi Sebastien,

Great and amazing work, but I would really really wish that the Interpreter supports versions 2 and 3.5 of the .NET Framework due to XP backward compatibility since Windows XP is not supported with .NET v4.5 and later. I tried running the Interpreter loaded with a couple of scripting APIs built but it kept on raising an Exception stating: **could not load "System." at Jint..ctor** with a reference to the calling object and Form, only later to realize that it actually required .NET v4.0 to run after testing it on a Windows 8/8.1 machine. Many of us still provide support for Windows XP users through our applications and would want to continue as so. Please please sir and the community at large, consider this as a burning issue, please...

Thank you.

**Comment by Willy-Kimura** [comment] 2015-09-11 21:00
Hi Sebastien,

Great and amazing work, but I would really really wish that the Interpreter supports versions 2 and 3.5 of the .NET Framework due to XP backward compatibility since Windows XP is not supported with .NET v4.5 and later. I tried running the Interpreter loaded with a couple of scripting APIs built but it kept on raising an Exception stating: **could not load "System." at Jint..ctor** with a reference to the calling object and Form, only later to realize that it actually required .NET v4.0 to run after testing it on a Windows 8/8.1 machine. Many of us still provide support for Windows XP users through our applications and would want to continue as so. Please please sir and the community at large, consider this as a burning issue, please...

Thank you.

**Comment by sebastienros** [comment] 2015-09-11 21:13
Duplicate of https://github.com/sebastienros/jint/issues/125

**Comment by sebastienros** [comment] 2015-09-11 21:14
Sorry, I don't want to put some work on this, I suggest you fork the repository and make the necessary changes for your scenario. Thanks for your support.

**Closed by sebastienros** 2015-09-11 21:13 UTC

**Comment by Willy-Kimura** [comment] 2015-09-11 22:15
Okay, am still really glad you're doing an amazing job sir, thanks hugely!
