### ISSUE TITLE
How do I make an "async/await" operator for Jint?

### ISSUE THREAD

**Issue by MauryDev** [sebastienros/jint#755] opened 2020-07-02 07:03 UTC
I made a function in C# for Promise, Async and Await, but I don't want it to be "async / await" functions in javascript, but an operator.

It works in my custom `Jint.Engine` like that

```js
var async_example = async(function()
{
  return 2;
})
var t = async_example();
console.log(await(t))
// 2
```
But I would like it that way:
```js
var async_example = async function()
{
  return 2;
}
var t = async_example();
console.log(await t)
// 2
```

I wanted to add the "async / await" operator to Jint. Please help me.

**Comment by danbopes** [comment] 2020-12-26 18:57
Promises have yet to have been implemented. (So no async/await yet)

**Comment by lahma** [comment] 2020-12-27 07:20
You might want to follow [the building block PR, Promises](https://github.com/sebastienros/jint/pull/643).

**Comment by lahma** [comment] 2021-12-11 16:02
Closing this as duplicate of #514 , we have the promises, but async/await needs to be done. I think generators need to be done as it has some building blocks once again.

**Closed by lahma** 2021-12-11 16:02 UTC

**Comment by lahma** [comment] 2022-10-20 19:06
`async`/`await` has been implemented as first class citizen in main branch.

**Comment by sfmskywalker** [comment] 2023-09-27 19:02
Hi @lahma , does this also mean one could set an C# function that returns a Task that can be awaited in JS? For example:

```csharp
engine.SetValue("testAsync", (Func<Task<object?>>)(async () => await Task.FromResult(new { foo = "bar" })));
```

I tried this with the following JS:

```javascript
const bar = await testAsync();
```

Which throws a `ParserException` with "Unexpected identifier".

**Comment by lahma** [comment] 2023-10-11 16:16
Sorry I've been a bit absent as my wife passed away a month ago and I had to prioritize things a bit.  I think there's a PR #1567 that tries to fill the gap between .NET Task and JS's async, but there might be dragons.

If you get `Unexpected identifier` that might signal that you are not in async context as that's something that is being expected by the parser at the moment (inside async function).

**Comment by sfmskywalker** [comment] 2023-10-18 06:58
Sorry for your loss Marko. I noticed you have merged that PR, which is fantastic - thank you! I'll go take a look.

**Comment by sfmskywalker** [comment] 2024-10-30 07:25
I never reported back, but I wanted to let you know that the bridging from Promise<T> to Task<T> and the async/await keywords work super amazing 😍
