### ISSUE TITLE
Cannot access Type property in JObject

### ISSUE THREAD

**Issue by bakkar1989** [sebastienros/jint#806] opened 2020-11-24 19:07 UTC
Type resolves to `Object.Type` when it should check of `JObject` indexer.

```csharp
[Fact]
public void AccessingJObjectPropertyViaArraysIntegerIndexShouldWork()
{
    const string json = @"{ ""Type"": ""Cat"" }";
    var jObjectWithTypeProperty = JObject.Parse(json);

    _engine.SetValue("o", jObjectWithTypeProperty);

    var typeResult = _engine.Execute("o.Type").GetCompletionValue();
    Assert.Equal("Cat", typeResult.AsString()); // System.ArgumentException: Expected string but got Integer
}
```

**Comment by lahma** [comment] 2020-11-24 19:15
Probably duplicate of #797

**Comment by bakkar1989** [comment] 2020-11-24 19:40
Hi yes, I downloaded the github source code and used that to parse my code and it worked. The version from nuget still not.

Thanks

**Comment by sebastienros** [comment] 2020-11-24 21:01
Weird, it should be  ... you can also use the myget feed which is documented in the readme, it contains the dev branch builds

**Comment by bakkar1989** [comment] 2020-11-25 21:51
Hi, now i am getting this anomaly, i can get the object from the array but when i try to access the property i get value 1

`            var jsonAnimals = @" { 
                    ""Animals"": 
                    [
                        {
                            ""Type"": ""Cat""
                        }
                    ]
                }
            ";

            JObject animals = JObject.Parse(jsonAnimals);
            testEngine.SetValue("animals", animals["Animals"]);

            testEngine.Execute("animals[0]");
            var typeResultObject = testEngine.GetCompletionValue(); // animals[0] = {{ "Type": "Cat" }}  

            testEngine.Execute("animals[0].Type");
            var typeResult = testEngine.GetCompletionValue(); // animals[0].Type = {1}
`

**Comment by lahma** [comment] 2020-11-26 06:24
The problem seems to be that reflection takes precedence here and resolves to `Object.Type`, should figure out more rules to target IDictionary<string, TValue>, IDictionary<int, TValue> before letting reflection to kick in.

**Comment by bakkar1989** [comment] 2020-11-26 07:52
Maybe this helps, I tried the same scenario with BsonDocument of MongoDB.Bson and it worked as expected, the only thing did not work are the conditions with the BsonInt32, BsonString and i guess with other types

'            var jsonAnimals = @" { 
                    ""Animals"": 
                    [
                        {
                            ""Id"":  1,
                            ""Type"": ""Cat""
                        }
                    ]
                }
            ";

            var bsonAnimals = BsonDocument.Parse(jsonAnimals);
            testEngine.SetValue("animals", bsonAnimals["Animals"]);

            testEngine.Execute("animals[0]");
            var typeResultObject = testEngine.GetCompletionValue(); // {{ "Type": "Cat" }}

            testEngine.Execute("animals[0].Type");
            var typeResult = testEngine.GetCompletionValue(); // {"Cat"}

            testEngine.Execute("animals[0].Type == 'Cat'");  // System.NotSupportedException: 'BsonString does not support indexing by name (only BsonDocument does).'
            var conditionResultString = testEngine.GetCompletionValue();

            testEngine.Execute("animals[0].Id == 1"); // System.NotSupportedException: 'BsonInt32 does not support indexing by name (only BsonDocument does).'
            var conditionResult = testEngine.GetCompletionValue();
'

**Closed** 2020-11-30 20:19 UTC
Labels: bug
