### ISSUE TITLE
[BUG] Implicit Conversion from CLR Interface to JSValue Behaviour Changed

### ISSUE THREAD

**Issue by Ayymoss** [sebastienros/jint#1768] opened 2024-01-31 00:34 UTC
**Version used**

The issue occurs on 3.0.0-beta-2051 and newer versions.

**Describe the bug**

For the below example. Interface properties no longer support accessing underlying implementation. For example, `IList` to `List`. 
Whilst this may be appropriate for user-defined interfaces, it breaks existing behaviour for framework-managed assemblies. 

I can no longer use JavaScript iterative methods on an interface that implements `IEnumerable`.

```
Jint.Runtime.JavaScriptException: Property 'forEach' of object is not a function
 ---> Error: Property 'forEach' of object is not a function
   at test (test) <anonymous>:1:23
   at <anonymous>:1:1
   --- End of inner exception stack trace ---
   at Jint.Runtime.ExceptionHelper.ThrowJavaScriptException(Engine engine, JsValue value, Completion& result)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArgument, JsValue[] arguments)
   at Jint.Engine.Call(FunctionInstance functionInstance, JsValue thisObject, JsValue[] arguments, JintExpression expression)
   at Jint.Engine.<>c__DisplayClass119_0.<Call>g__Callback|0()
   at Jint.Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback)
   at Jint.Engine.Call(JsValue callable, JsValue thisObject, JsValue[] arguments)
   at Jint.Engine.Call(JsValue callable, JsValue[] arguments)
   at Jint.Engine.Call(String callableName, JsValue[] arguments)
```

**To Reproduce**

```cs
using Jint;
using Jint.Native;

var engine = new Engine();
engine.Evaluate("function test(listTest) { listTest.list.forEach(x => 1); }");
var foo = JsValue.FromObject(engine, new ListTest());
var arguments = new[] {foo};
engine.Call("test", arguments);

public class ListTest
{
    public IList<int> List { get; set; } = new List<int>();
}
```

**Expected behaviour**

The code runs to completion without error.

**Additional context**

Using version 3.0.0-beta-2050 and below works without issue. (Tested to 2049)

**Comment by lahma** [comment] 2024-01-31 19:46
Could you maybe help with a PR?

**Comment by Ayymoss** [comment] 2024-01-31 22:31
Thank you for your response. Currently, I'm still quite new to C# and don't feel confident enough to contribute with a PR on this project. However, you might want to check with @viruscamp, as I believe the issue may have originated from changes in their recent PR.

**Comment by tom-b-iodigital** [comment] 2024-02-23 15:49
I've looked a bit into this issue. ForEach is not a method of IList but of List. So actually, this code also wouldn't work in C# without casting back to List. We might all find it strange that List has many more methods than IList, but that's the way it is ;).

However, strangely, SetValue treats this differently leading to following disrepancy.

```csharp

var engine = new Engine();

var listTest = new ListTest();

engine.SetValue("listTestCtx", listTest);
engine.SetValue("listCtx", listTest.List);
engine.SetValue("log", new Action<object>(Console.WriteLine));

engine.Evaluate("""

    listCtx.forEach(x => log(x));
    log("We got here");
    
    listTestCtx.List.forEach(x => log(x));
    log("We won't get here");
    
    """);

public class ListTest
{
    public IList<int> List { get; set; } = new List<int>() { 2, 3 };

    public IList<int> GetList()
    { 
        return List; 
    }
}

```

Outputs:

2
3
We got here
Unhandled exception. Jint.Runtime.JavaScriptException: Property 'forEach' of object is not a function

@lahma Is this intended behaviour or something you would like me to look at?

**Comment by tom-b-iodigital** [comment] 2024-02-23 15:57
I guess the discussion is, do we want the javascript code to be able to access the full object when passed an interface, or do we want to limit it to the interface properties en methods. 

The first case is more like you would expect javascript to behave. It would also not break existing code, which might happen if you "fix" the SetValue function. The second case is more how you would expect an OO language to behave and is more like it would be in C#.

**Comment by lahma** [comment] 2024-02-23 16:36
I think the problem is here:

https://github.com/sebastienros/jint/blob/3fbbff729c220008605c026b624c3f674251ba2d/Jint/Runtime/Interop/TypeDescriptor.cs#L48-L52

So we can handle `List` just fine (I guess), but the generic version `IList<T>` (and probably `IList` too) won't return the count property as it's declared in base interface. Also `IList<T>` doesn't inherit from `IList`, probably adding more smarts to that code block could help with this issue.

**Comment by tom-b-iodigital** [comment] 2024-02-23 16:38
I'll have a look

**Comment by tom-b-iodigital** [comment] 2024-02-23 16:53
@lahma just to be clear, this has nothing to do with Lists 

To make it more obvious, look at this example.

```csharp

var engine = new Engine();

var listTest = new ListTest();

engine.SetValue("listTestCtx", listTest);
engine.SetValue("listCtx", listTest.GetList());
engine.SetValue("helloCtx", listTest.Hello);
engine.SetValue("listCtx", listTest.GetList());
engine.SetValue("log", new Action<object>(Console.WriteLine));

engine.Evaluate("""

    listCtx.forEach(x => log(x));
    helloCtx.shout();
    log("We got here");

    listTestCtx.Hello.shout();    
    listTestCtx.List.forEach(x => log(x));
    log("We won't get here");
    
    """);

public class ListTest
{
    public IList<int> List { get; set; } = new List<int>() { 2, 3 };

    public IList<int> GetList()
    { 
        return List; 
    }

    public IHello Hello { get; set; } = new Hello();
}

public class Hello : IHello
{
    public void Shout()
    {
        Console.WriteLine("heeey");
    }
}

public interface IHello
{

}

```

The first shout will work, even though it debatably shouldn't. My proposal would be to make the second shout work too. Do you agree?

**Comment by lahma** [comment] 2024-02-23 17:01
I think the interface behavior relates to the fact that when people want to expose a member via interface (narrowing API), only interface members should be exposed. Seems that wrapping an object directly from engine interface (SetValue) doesn't respect that.

**Comment by tom-b-iodigital** [comment] 2024-02-23 17:04
yes, although as mentioned, javascript normally wouldn't care anyway. I'm willing to fix it both ways, but I do think the behaviour should be consistent :)

**Comment by lahma** [comment] 2024-02-23 17:08
JS rarely cares 😉 For interop I guess the scenario is for solutions to allow customer access to some specific platform features and using an interface would be ideal - instead of exposing `_myInternalCounter`. Either way I'm afraid something will be broken if visibility rules will be changed, but YOLO.

**Comment by tom-b-iodigital** [comment] 2024-02-23 17:09
I'll fix the SetValue method and everybody passing an interface and expecting to be able to call methods outside of the interface will cry 😂. PR coming up, probably tomorrow though

**Comment by lahma** [comment] 2024-02-23 17:16
I think that https://github.com/sebastienros/jint/issues/1768#issuecomment-1961644728 might still be broken though - at least some optimizations might be missing if we don't know about integer indexing possibility.

**Comment by lahma** [comment] 2024-02-24 08:13
> I think that [#1768 (comment)](https://github.com/sebastienros/jint/issues/1768#issuecomment-1961644728) might still be broken though - at least some optimizations might be missing if we don't know about integer indexing possibility.

Created #1788 to make type analysis logic check inherited interfaces too.

**Comment by lahma** [comment] 2024-02-24 09:04
OK after thinking this a bit more, some thoughts.

* `forEach` can be an unfortunate example here, it's mapped to `List<T>.ForEach`, which is CLR method instead of what you would get when injecting `T[]` into engine which would be converted to JsArray and would get JS prototype function
* if one exposes `IReadOnlyList<T>` from code I would assume that writing into backing `List<T>` isn't what is preferred (of course there's interop option `AllowWrite` too, but there are other examples as exposed mutator methods)
* one option could be to add Yet Another Interop option that would map the exposed type for object, defaulting to current "what is in the type property" and one could change this to return instance's actual type

**Comment by lahma** [comment] 2024-02-24 09:10
Ah, this can already be achieved with custom object wrapper actually.

```c#
var engine = new Engine(options =>
    options.SetWrapObjectHandler((e, target, type) => new ObjectWrapper(e, target, target.GetType()))
);
```

Should make the examples work.

**Comment by lahma** [comment] 2024-02-24 16:23
I'm closing this as behavior can be changed via engine configuration.

**Closed by lahma** 2024-02-24 16:23 UTC
