### ISSUE TITLE
Converts dates to UTC

### ISSUE THREAD

**Issue by dalenewman** [sebastienros/jint#256] opened 2016-01-06 17:08 UTC
If you pass in a local `DateTime`, it comes back out as UTC.  I tried changing the local time zone when creating the engine, but got the same result.  Is this the right behavior?  Thanks!

```csharp
        [Test]
        public void TestLocalDate() {
            var date = new DateTime(2016, 1, 1, 13, 0, 0, DateTimeKind.Local);
            var engine = new Engine().SetValue("localDate", date);
            engine.Execute(@"localDate");
            var actual = engine.GetCompletionValue().AsDate().ToDateTime();
            Assert.AreEqual(date, actual);
        }
```

**Comment by honestegg** [comment] 2016-01-06 17:25
What is the DateTimeKind of the returned DateTime object? Is it UTC? If so, and you convert that date to Local time, are the values equal?

**Comment by sebastienros** [comment] 2016-01-06 17:36
So apparently it's not a bug, just .NET behavior, to compare the dates you have to use the same timezone. In this case you can use `.ToUniversalTime()` on both before. Internally all JavaScript dates are converted to Utc, so the returned `DateTime` will be in Utc, whereas the one you provide is local.

See http://stackoverflow.com/questions/6930489/safely-comparing-local-and-universal-datetimes

**Closed by sebastienros** 2016-01-06 17:36 UTC
Labels: bug

**Comment by sebastienros** [comment] 2016-01-06 17:37
This test passes:

```
var date = new DateTime(2016, 1, 1, 13, 0, 0, DateTimeKind.Local);
var engine = new Engine().SetValue("localDate", date);
engine.Execute(@"localDate");
var actual = engine.GetCompletionValue().AsDate().ToDateTime();
Assert.Equal(date.ToUniversalTime(), actual.ToUniversalTime());
Assert.Equal(date.ToLocalTime(), actual.ToLocalTime());
```
