### ISSUE TITLE
Bug: Unable to roundtrip date with millisecond resolution

### ISSUE THREAD

**Issue by niemyjski** [sebastienros/jint#1496] opened 2023-03-14 21:15 UTC
I'm running the latest beta (https://github.com/sebastienros/jint/releases/tag/v3.0.0-beta-2047).

I'm running the scripts below like this:

```cs
var engine = new Engine(o => {
            o.LimitRecursion(64);
            o.MaxStatements(100);
            o.Strict();
            o.LocalTimeZone(TimeZoneInfo.Utc)
);
var completionValue = engine.Evaluate(script);
return completionValue.ToObject();
```

Let's say I have the following scripts:

```js
return new Date("2022-06-15T15:19:25.89Z");
```

This returns a completion value of:  `Wed Jun 15 2022 20:19:25 GMT+0000 (Coordinated Universal Time)` and a `ToObject` value of: `6/15/2022 8:19:25 PM` (`((DateTime)completionValue.ToObject()).ToString("O")` = `2022-06-15T20:19:25.0000000Z`)

```js
return new Date("2022-06-15T15:19:25.89Z").toISOString();
```

This returns `"2022-06-15T20:19:25.000Z"`

In either case I'd expect to get a value back with milliseconds: `2022-06-15T15:19:25.890Z`

**Comment by lahma** [comment] 2023-03-15 06:37
Can you try out latest preview from MyGet, a lot of work has gone recently into making date handling better.

**Comment by niemyjski** [comment] 2023-03-15 15:47
I just tried with the latest myget feed and it has the same issue.

**Comment by lahma** [comment] 2023-03-15 17:01
Can you write a failing unit test?

**Comment by lahma** [comment] 2023-03-15 17:37
For reference, here's a test case *that does not fail* in current main:

```c#
[Fact]
public void ShouldRetainMillisecondPrecision()
{
    var engine = new Engine(o => o.LocalTimeZone(TimeZoneInfo.Utc));
    Assert.Equal("2022-06-15T15:19:25.890Z", engine.Evaluate("new Date('2022-06-15T15:19:25.89Z').toISOString()"));
    Assert.Equal("2022-06-15T15:19:25.8900000Z", ((DateTime) engine.Evaluate("new Date('2022-06-15T15:19:25.89Z')").ToObject()).ToString("O"));
}
```

**Comment by lahma** [comment] 2023-03-18 12:31
Closing as cannot reproduce. We can reopen if there's a repro.

**Closed by lahma** 2023-03-18 12:31 UTC

**Comment by niemyjski** [comment] 2023-03-18 12:33
I will try to narrow down further as time permits, write a test for this and open a pr.
