### ISSUE TITLE
Exception thrown in constructor gives incorrect error

### ISSUE THREAD

**Issue by tottaka** [sebastienros/jint#847] opened 2021-03-12 01:09 UTC
I came across a bug where if an exception is thrown inside a c# constructor, Jint gives the following exception:
JavaScriptException: No public methods with the specified arguments were found.

Even though there is a public constructor method with the specified arguments. The exception on the C# which gets thrown inside the constructor method side is:
FileLoadException: Audio format is not supported.

So my concern is why the original exception isn't thrown, and instead it's giving me the "no public methods found" exception.. Any thoughts?

**Comment by Jither** [comment] 2021-04-06 00:01
I think this was fixed for method calls per issue https://github.com/sebastienros/jint/issues/42 - but not for constructors. I'm guessing the solution should be much the same for constructors:

https://github.com/sebastienros/jint/blob/70eb6444039603145ac822a2ffd5ba88524227a4/Jint/Runtime/Interop/TypeReference.cs#L97-L100

(where the exception is discarded, letting the flow continue to the exception thrown - "No public methods..." - if no matching constructor was found)

... as the solution for methods:

https://github.com/sebastienros/jint/blob/70eb6444039603145ac822a2ffd5ba88524227a4/Jint/Runtime/Interop/MethodInfoFunctionInstance.cs#L102-L109

Updated ShouldCatchAllClrExceptions in InteropTests for this case here (and swapped actual <-> expected in that test for good measure):
https://github.com/Jither/jint/commit/d0581f5dc7c31523a1150bff471206ec2db4f7e9

![image](https://user-images.githubusercontent.com/1401346/113640545-faee5800-967b-11eb-9267-69acb81c6591.png)

**Comment by Jither** [comment] 2021-04-06 00:11
Also: Duplicate of https://github.com/sebastienros/jint/issues/553

**Comment by lahma** [comment] 2021-04-06 18:34
Like @Jither said, I think the same logic fix is applicaple here too.

**Closed** 2021-04-09 14:36 UTC
