### ISSUE TITLE
Setting Value to Array inside an object is not work

### ISSUE THREAD

**Issue by zhixiao-kooboo** [sebastienros/jint#846] opened 2021-03-02 08:27 UTC
The code is like following
```CSharp
            var list = new List<int>();
            for(var i = 0; i < 10; i++)
            {
                list.Add(0);
            }
            var array = list.ToArray();
            array[2] = 2;
            var engine = new Jint.Engine()
                .SetValue("Test", new { Array = array });

            var script = @"
Test.Array[0]=1;
Test.Array[1]=2;
Test.Array[2]=3;";
            var arrayResult = engine.Execute(script).GetValue("Test").ToObject();

            Console.WriteLine(JsonConvert.SerializeObject(arrayResult));
```
All the values which I set to `Test.Array` are not working as expected.
Here is the output
`{"Array":[0,0,2,0,0,0,0,0,0,0]}`

But if I change the array on the root, it works
```CSharp
            var list = new List<int>();
            for(var i = 0; i < 10; i++)
            {
                list.Add(0);
            }
            var array = list.ToArray();
            array[2] = 2;
            var engine = new Jint.Engine()
                .SetValue("Test", array);

            var script = @"
Test[0]=1;
Test[1]=2;
Test[2]=3;";
            var arrayResult = engine.Execute(script).GetValue("Test").ToObject();

            Console.WriteLine(JsonConvert.SerializeObject(arrayResult));
            Console.ReadLine();
```

**Comment by friuns2** [comment] 2021-03-02 08:32
lol i have same problem

**Comment by zhixiao-kooboo** [comment] 2021-03-02 08:35
> lol i have same problem

Trying to debug with source code.

**Comment by lahma** [comment] 2021-03-02 08:58
Does it work if you don't use anonymous class as container for array, like a named class with getter and setter for array property?

**Comment by zhixiao-kooboo** [comment] 2021-03-02 09:05
Hi @lahma, thanks for the feedback, just tried, not working also
```
class Program
    {
        static void Main(string[] args)
        {
            var list = new List<int>();
            for(var i = 0; i < 10; i++)
            {
                list.Add(0);
            }
            var array = list.ToArray();
            var engine = new Jint.Engine()
                .SetValue("Test", new Test { Array = array });

            var script = @"
Test.Array[0]=1;
Test.Array[1]=2;
Test.Array[2]=3;";
            var arrayResult = engine.Execute(script).GetValue("Test").ToObject();

            Console.WriteLine(JsonConvert.SerializeObject(arrayResult));
            Console.ReadLine();
        }

        public class Test
        {
            public int[] Array { get; set; }
        }
    }
```

**Comment by zhixiao-kooboo** [comment] 2021-03-02 09:28
Adding a Unit test to source code to reproduce it
```
        [Fact]
        public void SetArrayValue()
        {
            var list = new List<int>();
            for (var i = 0; i < 10; i++)
            {
                list.Add(0);
            }
            var array = list.ToArray();
            _engine.SetValue("Test", new { Array = array });

            var script = @"
Test.Array[0]=1;
Test.Array[1]=2;
Test.Array[2]=3;
Test.Array[2]";
            var executedResult = _engine.Execute(script).GetValue("Test").ToObject();
            var executedResult2 = _engine.Execute(script).GetCompletionValue().ToObject();

            Assert.Equal(1, 1);
        }
```

**Comment by zhixiao-kooboo** [comment] 2021-03-02 10:18
Found a workaround
```CSharp
        [Fact]
        public void SetArrayValue()
        {
            var list = new List<int>();
            for (var i = 0; i < 10; i++)
            {
                list.Add(0);
            }
            var array = list.ToArray();
            _engine.SetValue("Test", new Test { Array = array });;

            var script = @"
var arr = Test.Array;
arr[2]=1;
Test.Array = arr;";

            var executedResult = _engine.Execute(script).GetValue("Test").ToObject();

            Assert.Equal(1, 1);
        }

        public class Test
        {
            public int[] Array { get; set; }
        }
```

**Comment by zhixiao-kooboo** [comment] 2021-03-05 06:09
Found a new idea to work around this bug
```CSharp
        static void Main(string[] args)
        {
            var context = new { Variables = new { Array = new int[] { 1, 2, 3 }, EmptyArray = new int[] { } }  };

            var array = new int[] { };
            var engine = new Jint.Engine()
                .SetValue("log",new Action<object>(Console.WriteLine));

            var script = @"Context.Variables.Array[0]=2;
Context.Variables.Array[3]=4;
Context.Variables.EmptyArray[0]=5
Context.Variables.EmptyArray[3]=5";

            var preScript = $"var Context = {JsonConvert.SerializeObject(context)};{Environment.NewLine}";

            var executedResult = engine.Execute(preScript + script).GetValue("Context").ToObject();

            Console.WriteLine(JsonConvert.SerializeObject(executedResult));
            Console.ReadLine();
        }
```

The result is `{"Variables":{"Array":[2.0,2.0,3.0,4.0],"EmptyArray":[5.0,null,null,5.0]}}`

**Comment by zhixiao-kooboo** [comment] 2021-03-05 07:37
@lahma And one more issue is that `.ToObject()` will convert all interger to double.

**Comment by lahma** [comment] 2021-03-05 08:41
I did a quick analysis yester day and the root cause is that Jint wraps array as JS array, I think in interop scenario it should be left as regular object wrapper allowing indexing. I think one would expect `engine.SetValue("myvar", new int [] { 1, 2, 3});` to be changed to JS array instance (allowing push/find etc), but not when accessing object's property.

**Comment by zhixiao-kooboo** [comment] 2021-03-08 01:24
@lahma Thanks for your investigation. For my scenario, the `Context` is a very dynamic object with nested properties (string, int.. object, array, the array of object, etc), so it's hard for me to use `engine.SetValue("myvar", new int [] { 1, 2, 3});`.
But my workaround solution solved my problem, so it's not a problem now.
And as you see, all integer numbers will be converted to double when I use `ToObject()` function, I think this also can be improved.

**Comment by lahma** [comment] 2022-07-16 17:08
As this is not as straightforward as one might think, I'm closing this and maybe we can raise separate issue if needed for specific use case(s).

**Closed by lahma** 2022-07-16 17:08 UTC
